import { Bursary } from "@/types/university";

export const EXTRA_BURSARIES_2: Bursary[] = [
  // Construction & Engineering
  {
    id: "murray-roberts-2025",
    name: "Murray & Roberts Bursary",
    provider: "Murray & Roberts",
    description: "Bursary for civil, mechanical, electrical and industrial engineering students.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering disciplines",
      "Strong academic performance"
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Murray & Roberts careers",
    contactInfo: "careers@murrob.com",
    fieldsOfStudy: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Industrial Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "wbho-2025",
    name: "WBHO Construction Bursary",
    provider: "WBHO Construction",
    description: "Bursary for civil engineering and construction management students.",
    amount: "Tuition + stipend + vacation employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying civil engineering or construction management",
      "Academic merit"
    ],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via WBHO careers",
    contactInfo: "bursaries@wbho.co.za",
    website: "https://www.wbho.co.za/careers/bursaries",
    fieldsOfStudy: ["Civil Engineering", "Construction Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "aveng-2025",
    name: "Aveng Group Bursary",
    provider: "Aveng Group",
    description: "Support for engineering and built environment fields.",
    amount: "Tuition + allowances + experiential learning",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering or built environment",
      "Academic merit"
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via Aveng careers",
    contactInfo: "careers@aveng.co.za",
    fieldsOfStudy: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Quantity Surveying"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "raubex-2025",
    name: "Raubex Bursary",
    provider: "Raubex Group",
    description: "Bursary for civil engineering, construction and materials engineering.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant disciplines", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Raubex careers",
    contactInfo: "careers@raubex.com",
    fieldsOfStudy: ["Civil Engineering", "Construction Management", "Materials Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "stefanutti-2025",
    name: "Stefanutti Stocks Bursary",
    provider: "Stefanutti Stocks",
    description: "Support for civil engineering and quantity surveying students.",
    amount: "Tuition + allowances + internship",
    eligibilityCriteria: ["South African citizen", "Studying civil engineering or QS", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Stefanutti Stocks careers",
    contactInfo: "careers@stefstocks.com",
    fieldsOfStudy: ["Civil Engineering", "Quantity Surveying"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },

  // ICT & Technology
  {
    id: "dimension-data-2025",
    name: "Dimension Data Bursary",
    provider: "Dimension Data / NTT",
    description: "Bursary for ICT, computer science and engineering.",
    amount: "Tuition + allowances + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying ICT/CS/Engineering", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Dimension Data careers",
    contactInfo: "careers@dimensiondata.com",
    fieldsOfStudy: ["Information Technology", "Computer Science", "Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "vodacom-technology-2025",
    name: "Vodacom Technology Bursary",
    provider: "Vodacom Group",
    description: "Expanded technology bursary for software engineering, data and networks.",
    amount: "Tuition + stipend + mentorship + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying ICT/engineering", "Academic excellence"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Vodacom careers",
    contactInfo: "foundation@vodacom.co.za",
    fieldsOfStudy: ["Software Engineering", "Data Science", "Network Engineering", "Information Systems"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "high"
  },
  {
    id: "unisa-ict-2025",
    name: "UNISA ICT Bursary",
    provider: "University of South Africa (UNISA)",
    description: "Faculty bursaries for outstanding ICT undergraduates.",
    amount: "Partial tuition + awards",
    eligibilityCriteria: ["Registered UNISA student", "High academic performance"],
    applicationDeadline: "Varies by call",
    applicationProcess: "Apply via UNISA student funding portal",
    contactInfo: "financialaid@unisa.ac.za",
    fieldsOfStudy: ["Information Technology", "Computer Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Strong academic record", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "unisabiz-2025",
    name: "UNISA College of Accounting Sciences Bursary",
    provider: "UNISA College of Accounting Sciences",
    description: "Support for accounting and auditing students at UNISA.",
    amount: "Partial tuition",
    eligibilityCriteria: ["Registered UNISA student", "Academic merit"],
    applicationDeadline: "Varies by call",
    applicationProcess: "Apply via UNISA funding portal",
    contactInfo: "cas-funding@unisa.ac.za",
    fieldsOfStudy: ["Accounting", "Auditing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // Insurance & Financial Services
  {
    id: "liberty-2025",
    name: "Liberty Actuarial Bursary",
    provider: "Liberty Group",
    description: "Prestigious bursary for actuarial science students.",
    amount: "Full tuition + stipend + mentorship + employment pathway",
    eligibilityCriteria: ["South African citizen", "Studying actuarial science", "Academic excellence"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Liberty careers",
    contactInfo: "careers@liberty.co.za",
    website: "https://www.liberty.co.za/careers",
    fieldsOfStudy: ["Actuarial Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "hollard-2025",
    name: "Hollard Bursary",
    provider: "Hollard",
    description: "Bursaries for actuarial, analytics and finance students.",
    amount: "Tuition + allowances + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying actuarial/finance/analytics", "Academic merit"],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via Hollard careers",
    contactInfo: "careers@hollard.co.za",
    fieldsOfStudy: ["Actuarial Science", "Finance", "Data Analytics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "High academic performance", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "fasset-2025",
    name: "FASSET Bursary",
    provider: "FASSET (Finance and Accounting Services SETA)",
    description: "Funding for finance and accounting studies in the FASSET sector.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying finance/accounting", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via FASSET projects",
    contactInfo: "info@fasset.org.za",
    website: "https://www.fasset.org.za/",
    fieldsOfStudy: ["Accounting", "Finance"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "merse-ta-2025",
    name: "merSETA Bursary",
    provider: "Manufacturing, Engineering and Related Services SETA",
    description: "Bursary for engineering and manufacturing-related studies.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying manufacturing/engineering", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via merSETA programmes",
    contactInfo: "info@merseta.org.za",
    website: "https://www.merseta.org.za/",
    fieldsOfStudy: ["Engineering", "Manufacturing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "mict-2025",
    name: "MICT SETA Bursary",
    provider: "MICT SETA",
    description: "Funding for media, information and communication technology programmes.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying ICT/media", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via MICT SETA",
    contactInfo: "info@mict.org.za",
    website: "https://www.mict.org.za/",
    fieldsOfStudy: ["Information Technology", "Media Studies", "Digital Marketing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "chieta-2025",
    name: "CHIETA Bursary",
    provider: "Chemical Industries Education & Training Authority",
    description: "Bursary for chemical industry-related qualifications.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying chemical industry fields", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via CHIETA",
    contactInfo: "info@chieta.org.za",
    website: "https://www.chieta.org.za/",
    fieldsOfStudy: ["Chemical Engineering", "Process Engineering", "Chemistry"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },

  // Healthcare & Pharma
  {
    id: "life-healthcare-2025",
    name: "Life Healthcare Bursary",
    provider: "Life Healthcare",
    description: "Bursary for nursing and allied health sciences.",
    amount: "Tuition + allowances + practical training",
    eligibilityCriteria: ["South African citizen", "Studying nursing/allied health", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Life Healthcare careers",
    contactInfo: "careers@lifehealthcare.co.za",
    fieldsOfStudy: ["Nursing", "Allied Health", "Healthcare Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "aspen-2025",
    name: "Aspen Pharmacare Bursary",
    provider: "Aspen Pharmacare",
    description: "Bursary for pharmacy, pharmaceutical sciences and related fields.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying pharmacy/pharmaceutical sciences", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Aspen careers",
    contactInfo: "careers@aspenpharma.com",
    fieldsOfStudy: ["Pharmacy", "Pharmaceutical Sciences", "Chemistry"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "adcock-2025",
    name: "Adcock Ingram Bursary",
    provider: "Adcock Ingram",
    description: "Support for pharmacy and health sciences students.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying pharmacy/health sciences", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Adcock Ingram careers",
    contactInfo: "careers@adcock.com",
    fieldsOfStudy: ["Pharmacy", "Health Sciences"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // FMCG & Manufacturing
  {
    id: "tiger-brands-2025",
    name: "Tiger Brands Bursary",
    provider: "Tiger Brands",
    description: "Bursary for engineering, food science and commerce.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant disciplines", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Tiger Brands careers",
    contactInfo: "careers@tigerbrands.com",
    fieldsOfStudy: ["Chemical Engineering", "Industrial Engineering", "Food Science", "Commerce"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "unilever-2025",
    name: "Unilever Bursary",
    provider: "Unilever South Africa",
    description: "Support for engineering, supply chain and marketing students.",
    amount: "Tuition + allowances + internship",
    eligibilityCriteria: ["South African citizen", "Studying engineering/supply chain/marketing", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Unilever careers",
    contactInfo: "careers.za@unilever.com",
    fieldsOfStudy: ["Chemical Engineering", "Supply Chain", "Marketing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "nestle-2025",
    name: "Nestlé South Africa Bursary",
    provider: "Nestlé South Africa",
    description: "Bursary for engineering, food science and commerce.",
    amount: "Tuition + stipend + internship",
    eligibilityCriteria: ["South African citizen", "Studying relevant fields", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Nestlé careers",
    contactInfo: "careers@za.nestle.com",
    fieldsOfStudy: ["Food Science", "Engineering", "Commerce"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "sab-2025",
    name: "SAB (AB InBev) Bursary",
    provider: "South African Breweries / AB InBev",
    description: "Support for brewing, engineering and supply chain studies.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant fields", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via AB InBev careers",
    contactInfo: "careers@ab-inbev.com",
    fieldsOfStudy: ["Chemical Engineering", "Mechanical Engineering", "Supply Chain", "Microbiology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },

  // Mining (additional)
  {
    id: "impala-platinum-2025",
    name: "Impala Platinum (Implats) Bursary",
    provider: "Implats",
    description: "Bursary for mining-related engineering and geosciences.",
    amount: "Tuition + stipend + vacation employment",
    eligibilityCriteria: ["South African citizen", "Studying mining engineering/geosciences", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Implats careers",
    contactInfo: "careers@implats.co.za",
    fieldsOfStudy: ["Mining Engineering", "Metallurgy", "Geology", "Electrical Engineering", "Mechanical Engineering"],
    provinces: ["North West", "Limpopo", "All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "amplats-2025",
    name: "Anglo American Platinum Bursary",
    provider: "Anglo American Platinum",
    description: "Bursary for engineering and mining disciplines in PGM sector.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant disciplines", "Academic excellence"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Anglo American careers",
    contactInfo: "careers@angloamerican.com",
    fieldsOfStudy: ["Mining Engineering", "Metallurgy", "Geology", "Electrical Engineering", "Mechanical Engineering"],
    provinces: ["Limpopo", "North West", "All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },

  // Banking (additional)
  {
    id: "fnb-2025",
    name: "FNB Bursary",
    provider: "First National Bank",
    description: "Support for IT, analytics and finance students.",
    amount: "Tuition + stipend + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying IT/analytics/finance", "Academic merit"],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via FNB careers",
    contactInfo: "graduates@fnb.co.za",
    fieldsOfStudy: ["Information Technology", "Data Science", "Finance", "Economics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "rmb-2025",
    name: "Rand Merchant Bank Bursary",
    provider: "RMB",
    description: "Bursary for quantitative finance, mathematics and technology.",
    amount: "Tuition + stipend + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying quant/finance/tech", "Academic excellence"],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via RMB careers",
    contactInfo: "graduates@rmb.co.za",
    fieldsOfStudy: ["Quantitative Finance", "Mathematics", "Computer Science", "Economics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },

  // Agriculture & Environment (additional)
  {
    id: "landbank-2025",
    name: "Land Bank Bursary",
    provider: "Land and Agricultural Development Bank of South Africa",
    description: "Funding for agriculture, agribusiness and related fields.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying agriculture/agribusiness", "Financial need"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Land Bank opportunities",
    contactInfo: "info@landbank.co.za",
    fieldsOfStudy: ["Agriculture", "Agribusiness", "Agricultural Economics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "dffe-2025",
    name: "Department of Forestry, Fisheries and the Environment Bursary",
    provider: "DFFE",
    description: "Bursary for environmental and natural resources studies.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying environmental/forestry/fisheries", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via DFFE bursaries",
    contactInfo: "info@dffe.gov.za",
    fieldsOfStudy: ["Environmental Science", "Forestry", "Fisheries", "Nature Conservation"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },

  // Transport & Logistics (additional)
  {
    id: "saa-2025",
    name: "South African Airways Bursary",
    provider: "South African Airways",
    description: "Support for aviation, aeronautical engineering and logistics.",
    amount: "Tuition + allowances + training",
    eligibilityCriteria: ["South African citizen", "Studying aviation/engineering/logistics", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via SAA careers",
    contactInfo: "careers@flysaa.com",
    fieldsOfStudy: ["Aeronautical Engineering", "Logistics", "Aviation Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "transnet-port-2025",
    name: "Transnet National Ports Authority Bursary",
    provider: "TNPA / Transnet",
    description: "Bursary for maritime studies, engineering and logistics.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying maritime/engineering/logistics", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via Transnet careers",
    contactInfo: "bursaries@transnet.net",
    fieldsOfStudy: ["Maritime Studies", "Mechanical Engineering", "Electrical Engineering", "Logistics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },

  // Municipalities (additional)
  {
    id: "tshwane-2025",
    name: "City of Tshwane Bursary",
    provider: "City of Tshwane",
    description: "Bursary for critical skills including engineering, health and finance.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Gauteng resident", "Studying scarce skills", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via City of Tshwane website",
    contactInfo: "bursaries@tshwane.gov.za",
    fieldsOfStudy: ["Engineering", "Health Sciences", "Finance", "IT"],
    provinces: ["Gauteng"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "ekurhuleni-2025",
    name: "City of Ekurhuleni Bursary",
    provider: "City of Ekurhuleni",
    description: "Funding for engineering, finance and ICT students.",
    amount: "Tuition + stipend + internship",
    eligibilityCriteria: ["South African citizen", "Ekurhuleni resident", "Studying scarce skills", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via City of Ekurhuleni website",
    contactInfo: "bursaries@ekurhuleni.gov.za",
    fieldsOfStudy: ["Engineering", "Finance", "ICT"],
    provinces: ["Gauteng"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "nmbm-2025",
    name: "Nelson Mandela Bay Municipality Bursary",
    provider: "Nelson Mandela Bay Municipality",
    description: "Bursary for engineering, finance and built environment.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Eastern Cape resident", "Studying scarce skills", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via NMBM website",
    contactInfo: "bursaries@nmbm.gov.za",
    fieldsOfStudy: ["Engineering", "Finance", "Built Environment"],
    provinces: ["Eastern Cape"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "mangaung-2025",
    name: "Mangaung Metropolitan Municipality Bursary",
    provider: "Mangaung Metro",
    description: "Funding for critical skills including engineering and health.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Free State resident", "Studying scarce skills"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via Mangaung website",
    contactInfo: "bursaries@mangaung.co.za",
    fieldsOfStudy: ["Engineering", "Health Sciences", "Finance"],
    provinces: ["Free State"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // Education & Teaching (additional)
  {
    id: "sace-2025",
    name: "SACE Teacher Education Bursary",
    provider: "South African Council for Educators",
    description: "Support for students pursuing teacher education programmes.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying ITE programmes", "Academic merit"],
    applicationDeadline: "31 October annually",
    applicationProcess: "Apply via SACE",
    contactInfo: "info@sace.org.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // Science & Research (additional)
  {
    id: "sarao-2025",
    name: "SARAO (SKA) Scholarship/Bursary",
    provider: "South African Radio Astronomy Observatory",
    description: "Funding for astronomy, engineering and data science aligned to SKA.",
    amount: "Tuition + stipend + research support",
    eligibilityCriteria: ["South African citizen", "Studying astronomy/engineering/data", "Academic excellence"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via SARAO",
    contactInfo: "bursary@ska.ac.za",
    website: "https://www.sarao.ac.za/students-and-graduates/",
    fieldsOfStudy: ["Astronomy", "Radio Engineering", "Data Science", "Computer Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "nrf-2025",
    name: "NRF Postgraduate Bursaries",
    provider: "National Research Foundation",
    description: "Postgraduate bursaries across science, engineering and technology.",
    amount: "Tuition + stipend + research costs",
    eligibilityCriteria: ["South African citizen/permanent resident", "Postgraduate studies", "Academic excellence"],
    applicationDeadline: "Varies by call",
    applicationProcess: "Apply via NRF Online Submission system",
    contactInfo: "support@nrf.ac.za",
    website: "https://www.nrf.ac.za/",
    fieldsOfStudy: ["Science", "Engineering", "Technology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic record", financialNeed: false },
    isActive: true,
    priority: "high"
  }
];
