export const CREATE_LISTING_CATEGORIES: string[] = [
  "Mystery",
  "Action",
  "Romance",
  "Sci‑Fi",
  "Fantasy",
  "Thriller",
  "Non‑Fiction",
  "Classics",
  "Historical",
  "Young Adult",
  "Graphic Novel",
  "Biography",
  "Poetry",
  "Short Stories",
  "Horror",
  "Literary Fiction",
  "Contemporary",
  "Essays",
  "Adventure",
  "Other",
].sort((a, b) => a.localeCompare(b));
