export const BASE_CATEGORIES = [
  "Computer Science",
  "Mathematics",
  "Biology",
  "Chemistry",
  "Physics",
  "Economics",
  "Psychology",
  "English",
  "History",
  "Geography",
  "Business Studies",
  "Accounting",
  "Life Sciences",
  "Physical Sciences",
  "Engineering",
  "Medicine",
  "Law",
  "Arts",
  "Languages",
  "Reader",
  "Other",
];

export const ADDITIONAL_CATEGORIES = [
  "Afrikaans Home Language",
  "Afrikaans First Additional Language",
  "English Home Language",
  "English First Additional Language",
  "isiXhosa Home Language",
  "isiXhosa First Additional Language",
  "isiZulu Home Language",
  "isiZulu First Additional Language",
  "Sepedi (Northern Sotho) Home Language",
  "Sepedi First Additional Language",
  "Sesotho Home Language",
  "Sesotho First Additional Language",
  "Setswana Home Language",
  "Setswana First Additional Language",
  "Xitsonga Home Language",
  "Xitsonga First Additional Language",
  "French",
  "German",
  "Portuguese",
  "Spanish",
  "Italian",
  "Other foreign languages",
  "Mathematical Literacy",
  "Physical Sciences",
  "Life Sciences (Biology)",
  "Agricultural Sciences",
  "Environmental Management",
  "Economics",
  "Entrepreneurship",
  "Financial Literacy",
  "Tourism",
  "Hospitality Studies",
  "Engineering Graphics and Design (EGD)",
  "Information Technology (IT)",
  "Computer Applications Technology (CAT)",
  "Technology (General)",
  "Music Technology",
  "Visual Arts",
  "Music",
  "Drama / Performing Arts",
  "Dance Studies",
  "Media Studies",
  "Design / Graphic Design",
  "History",
  "Geography",
  "Psychology (private or Cambridge schools)",
  "Sociology (private or Cambridge schools)",
  "Religious Studies / Theology",
  "Life Orientation (LO)",
  "Consumer Studies",
  "Sports Science / Physical Education",
];

export const CREATE_LISTING_CATEGORIES: string[] = Array.from(
  new Map(
    [...BASE_CATEGORIES, ...ADDITIONAL_CATEGORIES].map((c) => [
      c.trim().toLowerCase(),
      c.trim(),
    ])
  ).values()
).sort((a, b) => a.localeCompare(b));
