// Universities of Technology 2025 - Complete programs from document
import { University } from "@/types/university";

// Helper function to create degree objects
const createDegree = (
  name: string,
  apsRequirement: number,
  faculty: string,
  description?: string,
  duration: string = "3-4 years",
  subjects: Array<{ name: string; level: number; isRequired: boolean }> = [],
  careerProspects: string[] = []
) => ({
  id: name.toLowerCase().replace(/[^a-z0-9]/g, '-'),
  name,
  faculty,
  duration,
  apsRequirement,
  description: description || `Study ${name} at university level.`,
  subjects: subjects.length > 0 ? subjects : [
    { name: "English", level: 4, isRequired: true },
    { name: "Mathematics", level: 4, isRequired: true },
  ],
  careerProspects: careerProspects.length > 0 ? careerProspects : [
    "Professional in field",
    "Researcher",
    "Consultant",
    "Academic",
    "Specialist"
  ],
});

export const UNIVERSITIES_OF_TECHNOLOGY_2025: University[] = [
  // Cape Peninsula University of Technology (CPUT)
  {
    id: "cput",
    name: "Cape Peninsula University of Technology",
    abbreviation: "CPUT",
    fullName: "Cape Peninsula University of Technology",
    type: "University of Technology",
    location: "Cape Town, Western Cape",
    website: "https://www.cput.ac.za",
    logo: "/university-logos/cput.svg",
    description: "A technology-focused university offering practical and industry-relevant programs.",
    establishedYear: 2005,
    studentCount: 32000,
    campuses: ["Bellville Campus", "Cape Town Campus", "Mowbray Campus", "Wellington Campus"],
    faculties: [
      {
        name: "Agriculture & Natural Sciences",
        degrees: [
          createDegree("Diploma in Agriculture", 28, "Agriculture"),
          createDegree("Diploma in Agricultural Management", 28, "Agriculture"),
          createDegree("Diploma in Analytical Chemistry", 28, "Science"),
          createDegree("Diploma in Biotechnology", 28, "Science"),
          createDegree("Diploma in Consumer Science: Food & Nutrition", 26, "Science"),
          createDegree("Diploma in Environmental Management", 26, "Science"),
        ],
      },
      {
        name: "Health & Wellness Sciences",
        degrees: [
          createDegree("Bachelor of Health Sciences: Medical Laboratory Science", 38, "Health Sciences"),
          createDegree("Bachelor of Health Sciences: Medical Laboratory Science - Extended", 30, "Health Sciences"),
        ],
      },
    ],
    contactInfo: {
      email: "info@cput.ac.za",
      phone: "+27 21 460 3911",
      address: "PO Box 1906, Bellville, 7535",
    },
    applicationPeriods: {
      undergraduate: "April - September",
      postgraduate: "April - November",
    },
    notableFeatures: [
      "Industry partnerships",
      "Practical training focus",
      "Technology innovation",
    ],
  },

  // Central University of Technology (CUT)
  {
    id: "cut",
    name: "Central University of Technology",
    abbreviation: "CUT",
    fullName: "Central University of Technology, Free State",
    type: "University of Technology",
    location: "Bloemfontein, Free State",
    website: "https://www.cut.ac.za",
    logo: "/university-logos/cut.svg",
    description: "A technology university focused on applied sciences and professional training.",
    establishedYear: 1981,
    studentCount: 15000,
    campuses: ["Bloemfontein Campus", "Welkom Campus"],
    faculties: [
      {
        name: "Engineering, Built Environment & Information Technology",
        degrees: [
          createDegree("Diploma in Civil Engineering", 27, "Engineering"),
          createDegree("Diploma in Mechanical Engineering Technology", 27, "Engineering"),
          createDegree("Bachelor of Engineering Technology in Mechanical Engineering", 32, "Engineering"),
          createDegree("Diploma in Information Technology", 27, "Science"),
          createDegree("Bachelor of Information Technology", 30, "Science"),
        ],
      },
      {
        name: "Health & Environmental Sciences",
        degrees: [
          createDegree("Bachelor of Health Sciences: Medical Laboratory Sciences", 30, "Health Sciences"),
          createDegree("Diploma in Environmental Health", 27, "Health Sciences"),
          createDegree("Diploma in Dental Assisting", 27, "Health Sciences"),
        ],
      },
      {
        name: "Management Sciences & Humanities",
        degrees: [
          createDegree("Diploma in Public Management", 27, "Commerce"),
          createDegree("Diploma in Marketing", 27, "Commerce"),
          createDegree("Diploma in Internal Auditing", 28, "Commerce"),
          createDegree("Diploma in Office Management & Technology", 27, "Commerce"),
          createDegree("Bachelor of Hospitality Management", 30, "Commerce"),
          createDegree("Bachelor of Accountancy", 30, "Commerce"),
          createDegree("Bachelor of Tourism Management", 30, "Commerce"),
        ],
      },
      {
        name: "Education",
        degrees: [
          createDegree("Bachelor of Education (Foundation Phase)", 27, "Education"),
          createDegree("Bachelor of Education (SP & FET - Economics)", 27, "Education"),
          createDegree("Bachelor of Education (SP & FET - Natural Science)", 27, "Education"),
          createDegree("Bachelor of Education (SP & FET - Languages)", 27, "Education"),
          createDegree("Bachelor of Education (SP & FET - Mathematics)", 27, "Education"),
          createDegree("Bachelor of Education (SP & FET - Computer Science)", 27, "Education"),
        ],
      },
    ],
    contactInfo: {
      email: "info@cut.ac.za",
      phone: "+27 51 507 3911",
      address: "Private Bag X20539, Bloemfontein, 9300",
    },
    applicationPeriods: {
      undergraduate: "April - September",
      postgraduate: "April - November",
    },
    notableFeatures: [
      "Applied research focus",
      "Industry partnerships",
      "Technology innovation",
    ],
  },

  // Durban University of Technology (DUT)
  {
    id: "dut",
    name: "Durban University of Technology",
    abbreviation: "DUT",
    fullName: "Durban University of Technology",
    type: "University of Technology",
    location: "Durban, KwaZulu-Natal",
    website: "https://www.dut.ac.za",
    logo: "/university-logos/dut.svg",
    description: "A comprehensive technology university with strong industry connections.",
    establishedYear: 2002,
    studentCount: 31000,
    campuses: ["Steve Biko Campus", "ML Sultan Campus", "Ritson Campus", "Indumiso Campus"],
    faculties: [
      {
        name: "Accounting and Informatics",
        degrees: [
          createDegree("Bachelor of Information and Communications Technology", 30, "Science"),
          createDegree("Bachelor of ICT: Internet of Things (IoT)", 30, "Science"),
          createDegree("Diploma ICT: Applications Development", 23, "Science"),
          createDegree("Diploma ICT: Applications Development (Indumiso)", 23, "Science"),
          createDegree("Diploma ICT: Applications Development (Foundation)", 23, "Science"),
          createDegree("Diploma ICT: Business Analysis", 23, "Science"),
          createDegree("Diploma ICT: Business Analysis (Indumiso)", 23, "Science"),
          createDegree("Diploma Business & Information Management", 23, "Commerce"),
          createDegree("Diploma Business & Information Management (PMB)", 23, "Commerce"),
          createDegree("Diploma in Accounting", 23, "Commerce"),
          createDegree("Diploma in Accounting (PMB)", 23, "Commerce"),
          createDegree("Diploma in Accounting (Foundation)", 23, "Commerce"),
          createDegree("Diploma in Accounting (Foundation, PMB)", 23, "Commerce"),
          createDegree("Diploma in Business and Information (Foundation)", 23, "Commerce"),
          createDegree("Diploma in Internal Auditing", 23, "Commerce"),
          createDegree("Diploma in Internal Auditing (Foundation)", 23, "Commerce"),
          createDegree("Diploma in Library and Information Studies", 23, "Humanities"),
          createDegree("Diploma in Management Accounting", 23, "Commerce"),
          createDegree("Diploma in Management Accounting (PMB)", 23, "Commerce"),
          createDegree("Diploma in Taxation", 23, "Commerce"),
          createDegree("Diploma in Taxation (Foundation)", 23, "Commerce"),
        ],
      },
      {
        name: "Applied Sciences",
        degrees: [
          createDegree("Bachelor of Applied Science in Biotechnology", 28, "Science"),
          createDegree("Bachelor of Applied Science in Food Science and Technology", 28, "Science"),
          createDegree("Bachelor of Applied Science in Industrial Chemistry", 28, "Science"),
          createDegree("Bachelor of Applied Science in Textile Science", 28, "Science"),
          createDegree("Bachelor of Sport Science and Management", 28, "Health Sciences"),
          createDegree("Diploma in Shipping & Logistics", 23, "Commerce"),
          createDegree("Diploma in Analytical Chemistry", 23, "Science"),
          createDegree("Diploma in Clothing Management", 23, "Science"),
          createDegree("Diploma in Consumer Sciences in Food and Nutrition", 23, "Science"),
          createDegree("Diploma in Nautical Science", 23, "Science"),
          createDegree("Diploma in Sustainable Horticulture and Landscaping", 23, "Agriculture"),
          createDegree("Higher Certificate in Sport Management Science", 24, "Health Sciences"),
        ],
      },
      {
        name: "Arts and Design",
        degrees: [
          createDegree("Bachelor of Applied Arts in Commercial Photography", 26, "Humanities"),
          createDegree("Bachelor of Applied Arts in Screen Arts and Technology", 36, "Humanities"),
          createDegree("Bachelor of Design in Visual Communication Design", 26, "Humanities"),
          createDegree("Bachelor of Education in Senior Phase & FET: Economic and Management Sciences", 28, "Education"),
          createDegree("Bachelor of Education in Senior Phase & FET: Electrical Technology", 28, "Education"),
          createDegree("Bachelor of Education in Senior Phase & FET: Mechanical Technology", 28, "Education"),
          createDegree("Bachelor of Education in Senior Phase & FET: Languages", 28, "Education"),
          createDegree("Bachelor of Education in Senior Phase & FET: Natural Sciences", 28, "Education"),
          createDegree("Bachelor of Education in Senior Phase & FET: Civil Technology", 28, "Education"),
          createDegree("Bachelor of Journalism", 26, "Humanities"),
          createDegree("Diploma in Drama", 24, "Humanities"),
          createDegree("Diploma in Fashion Design", 23, "Humanities"),
          createDegree("Diploma in Fine Art", 23, "Humanities"),
          createDegree("Diploma in Interior Design", 23, "Humanities"),
          createDegree("Diploma in Jewellery Design and Manufacture", 23, "Humanities"),
          createDegree("Diploma in Language Practice", 23, "Humanities"),
          createDegree("Higher Certificate in Performing Arts Technology", 23, "Humanities"),
        ],
      },
      {
        name: "Engineering and the Built Environment",
        degrees: [
          createDegree("Bachelor of the Built Environment: Urban and Regional Planning", 26, "Engineering"),
          createDegree("Bachelor of Engineering Technology in Chemical Engineering", 26, "Engineering"),
          createDegree("Bachelor of Engineering Technology in Electronic Engineering", 26, "Engineering"),
          createDegree("Bachelor of Engineering Technology in Industrial Engineering", 26, "Engineering"),
          createDegree("Bachelor of Engineering Technology in Mechanical Engineering", 26, "Engineering"),
          createDegree("Bachelor of Engineering Technology in Power Engineering", 26, "Engineering"),
          createDegree("Bachelor of the Built Environment in Architecture", 26, "Engineering"),
          createDegree("Bachelor of the Built Environment in Construction Studies", 26, "Engineering"),
          createDegree("Bachelor of the Built Environment in Geomatics", 26, "Engineering"),
          createDegree("Bachelor of Engineering Technology in Civil Engineering", 26, "Engineering"),
          createDegree("Diploma in Engineering Technology in Civil Engineering", 26, "Engineering"),
          createDegree("Diploma in the Built Environment in Construction Studies", 26, "Engineering"),
          createDegree("Diploma in Pulp and Paper Technology", 23, "Engineering"),
        ],
      },
      {
        name: "Health Sciences",
        degrees: [
          createDegree("Bachelor of Child & Youth Care", 26, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Environmental Health", 26, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Radiography: Diagnostic", 28, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Radiography: Sonography", 28, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Radiography: Therapy and Oncology", 28, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Clinical Technology", 26, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Emergency Medical Care", 30, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Homeopathy", 26, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Chiropractic", 26, "Health Sciences"),
          createDegree("Bachelor of Health Sciences in Medical Laboratory Science", 26, "Health Sciences"),
          createDegree("Bachelor in Nursing", 28, "Health Sciences"),
          createDegree("Diploma in Somatology", 23, "Health Sciences"),
          createDegree("Higher Certificate in Dental Assisting", 23, "Health Sciences"),
        ],
      },
      {
        name: "Management Sciences",
        degrees: [
          createDegree("Diploma in Management Sciences: Business Administration", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Business Administration (PMB)", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Business Law", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Business Administration (ECP, PMB)", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Human Resources", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Human Resources (PMB)", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Human Resources (Part-Time)", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Marketing", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Operations", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Operations (Part-Time)", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Public Relations and Communication", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Public Relations (PMB)", 25, "Commerce"),
          createDegree("Diploma in Management Sciences: Retail", 25, "Commerce"),
          createDegree("Diploma in Public Administration: Disaster & Risk Management", 25, "Commerce"),
          createDegree("Diploma in Public Administration: Local Government", 25, "Commerce"),
          createDegree("Diploma in Public Administration: Public Management", 25, "Commerce"),
          createDegree("Diploma in Public Administration: Public Management (PMB)", 25, "Commerce"),
          createDegree("Diploma in Public Administration: Supply Chain Management", 25, "Commerce"),
          createDegree("Diploma in Public Administration: Supply Chain Management (PMB)", 25, "Commerce"),
          createDegree("Diploma in Catering Management", 23, "Commerce"),
          createDegree("Diploma in Hospitality Management", 23, "Commerce"),
          createDegree("Diploma in Tourism Management", 26, "Commerce"),
          createDegree("Diploma in Eco Tourism", 25, "Commerce"),
        ],
      },
    ],
    contactInfo: {
      email: "info@dut.ac.za",
      phone: "+27 31 373 2000",
      address: "PO Box 1334, Durban, 4000",
    },
    applicationPeriods: {
      undergraduate: "April - September",
      postgraduate: "April - November",
    },
    notableFeatures: [
      "Strong industry partnerships",
      "Practical skills development",
      "Comprehensive technology programs",
    ],
  },

  // Continue with more Universities of Technology...
  // Mangosuthu University of Technology (MUT)
  {
    id: "mut",
    name: "Mangosuthu University of Technology",
    abbreviation: "MUT",
    fullName: "Mangosuthu University of Technology",
    type: "University of Technology",
    location: "Umlazi, KwaZulu-Natal",
    website: "https://www.mut.ac.za",
    logo: "/university-logos/mut.svg",
    description: "A technology university focusing on engineering, management, and natural sciences.",
    establishedYear: 1979,
    studentCount: 13000,
    campuses: ["Umlazi Campus"],
    faculties: [
      {
        name: "Engineering",
        degrees: [
          createDegree("Diploma in Chemical Engineering", 26, "Engineering"),
          createDegree("Diploma in Civil Engineering", 26, "Engineering"),
          createDegree("Diploma in Surveying", 26, "Engineering"),
          createDegree("Diploma in Building", 26, "Engineering"),
          createDegree("Diploma in Electrical Engineering", 26, "Engineering"),
          createDegree("Diploma in Mechanical Engineering", 26, "Engineering"),
          createDegree("Bridging: Chemical Engineering", 20, "Engineering"),
          createDegree("Bridging: Civil Engineering", 20, "Engineering"),
          createDegree("Bridging: Electrical Engineering", 20, "Engineering"),
          createDegree("Bridging: Mechanical Engineering", 20, "Engineering"),
          createDegree("Bridging: Building", 20, "Engineering"),
          createDegree("Bridging: Surveying", 20, "Engineering"),
        ],
      },
      {
        name: "Management Sciences",
        degrees: [
          createDegree("Diploma in Accounting", 25, "Commerce"),
          createDegree("Diploma in Finance & Accounting: Public", 25, "Commerce"),
          createDegree("Diploma in Human Resource Management", 25, "Commerce"),
          createDegree("Diploma in Marketing", 25, "Commerce"),
          createDegree("Diploma in Office Management & Technology", 25, "Commerce"),
          createDegree("Diploma in Public Management", 25, "Commerce"),
        ],
      },
      {
        name: "Natural Sciences",
        degrees: [
          createDegree("BSc in Environmental Health", 26, "Health Sciences"),
          createDegree("Bachelor of Health Science in Medical Laboratory Sciences (BHSc-MLS)", 26, "Health Sciences"),
          createDegree("Diploma in Agriculture", 23, "Agriculture"),
          createDegree("Diploma in Biomedical Science", 26, "Science"),
          createDegree("Diploma in Analytical Chemistry", 26, "Science"),
          createDegree("Diploma in Community Extension", 23, "Science"),
          createDegree("Diploma in Nature Conservation", 23, "Science"),
          createDegree("Diploma in Information Technology", 23, "Science"),
        ],
      },
    ],
    contactInfo: {
      email: "info@mut.ac.za",
      phone: "+27 31 907 7911",
      address: "Private Bag X54323, Durban, 4000",
    },
    applicationPeriods: {
      undergraduate: "April - September",
      postgraduate: "April - November",
    },
    notableFeatures: [
      "Engineering excellence",
      "Community focus",
      "Industry partnerships",
    ],
  },

  // Add more UoTs here...
];

export default UNIVERSITIES_OF_TECHNOLOGY_2025;
