// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tefjsvwybbfecdilmvor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZmpzdnd5YmJmZWNkaWxtdm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MDY3OTcsImV4cCI6MjA3NjQ4Mjc5N30.kPx3yqB5AuMnZ1JPxtQ4OO8bmkR1EFsFkD7EQW9RL7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});